/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author acer
 */
public class LoginForm extends javax.swing.JFrame {
    private Connection conn;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Log In");
        this.conn = Koneksi.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLogin = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bLogin)
                    .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(pfPassword))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bLogin)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        String user = tfUsername.getText();
        
        String pass = String.valueOf(pfPassword.getPassword());
       
        if(tfUsername.getText().equals("") || pfPassword.getPassword().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Username Atau Password Tidak Boleh Kosong");
        }else {
            String query = "SELECT * FROM pegawai WHERE username = '"+user+"'";
            try {
                PreparedStatement ps = this.conn.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                boolean loged = false, status = false;
                while(rs.next()){
                    if(rs.getString("username").equals(user) && rs.getString("password").equals(pass)){
                        loged = true;
                        if(rs.getString("status").equals("admin")){
                            status = true;
                        }
                        break;
                    }
                }
                if(loged == true && status == true){
                    JOptionPane.showMessageDialog(this, "Login Berhasil");
                    new Admin().setVisible(true);
                    this.dispose();
                }
                else if(loged == true){
                    JOptionPane.showMessageDialog(this, "Login Berhasil");
                    new KedaiHp().setVisible(true);
                    this.dispose();
                }else {
                    JOptionPane.showMessageDialog(this, "Login Gagal");
                }
                rs.close();
                ps.close();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terdapat Masalah Ke Database"+ex.toString());
            }
            
//        try{
//            Connection c = Koneksi.connect();
//            Statement s = c.createStatement();
//            String sql = "SELECT username, password FROM pegawai where username='"+tfUsername.getText() + "' and password='"+ pfPassword.getText() +"'";
//            ResultSet rs = s.executeQuery(sql);
//            String status = "SELECT status FROM pegawai where username='"+tfUsername.getText() + "' and password='"+ pfPassword.getText() +"'";
//                
//            int baris = 0;
//            while (rs.next()) {
//                baris = rs.getRow();
//            }
//            
//            
//            if (baris ==1) {
//                JOptionPane.showMessageDialog(null,"Berhasil Login");
//                if("admin".equals(status)){
//                    new Admin().setVisible(true);
//                }
//            }else {
//                JOptionPane.showMessageDialog(null,"Gagal Login");
//            }
//        }catch(SQLException e){
//           
//        }
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
        bLogin.requestFocus();        
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
        pfPassword.requestFocus();
    }//GEN-LAST:event_tfUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
