/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author acer
 */
public class LoginForm extends javax.swing.JFrame {
    
    private Connection conn;
    String user;
//    private ResultSet rs;
   
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Log In");
        this.conn = Koneksi.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLogin = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        bLogin.setBackground(new java.awt.Color(255, 255, 255));
        bLogin.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        bLogin.setForeground(new java.awt.Color(102, 255, 102));
        bLogin.setBorderPainted(false);
        bLogin.setContentAreaFilled(false);
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bLogin);
        bLogin.setBounds(240, 390, 100, 50);

        tfUsername.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        tfUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfUsername.setBorder(null);
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfUsername);
        tfUsername.setBounds(100, 220, 190, 30);

        pfPassword.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        pfPassword.setBorder(null);
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pfPassword);
        pfPassword.setBounds(100, 307, 190, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/gambar/LoginForm.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 500);

        setSize(new java.awt.Dimension(416, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        user = tfUsername.getText();
        String pass = String.valueOf(pfPassword.getPassword());

       
        if(tfUsername.getText().equals("") || pfPassword.getPassword().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Username atau Password Tidak Boleh Kosong");
        }else {
            String query = "SELECT * FROM pegawai WHERE username = '"+user+"'";
            try {
                PreparedStatement ps = this.conn.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                boolean loged = false, akses = false, status = false;
                while(rs.next()){
                    if(rs.getString("username").equals(user) && rs.getString("password").equals(pass) && rs.getString("status").equalsIgnoreCase("Aktif")){
                        loged = true; status = true; 
                        if(rs.getString("akses").equals("admin")){
                            akses = true;
                        }
                        break;
                    }else if(rs.getString("username").equals(user) && rs.getString("password").equals(pass)){
                        loged = true; status = false;                         
                    }
                }
                if(loged == true && akses == true && status == true){
//                    JOptionPane.showMessageDialog(this, "Login Berhasil");
                    new Admin(user).setVisible(true);
                    this.dispose();
                }else if(loged == true && status == false){
                    JOptionPane.showMessageDialog(this, "Akun anda sedang di nonaktifkan.\n\n Harap menghubungi Admin");
                    tfUsername.setText("");
                    pfPassword.setText("");
                }else if(loged == true){
//                    JOptionPane.showMessageDialog(this, "Login Berhasil");
                    new KedaiHp(user).setVisible(true);
                    this.dispose();
                }else if(loged ==false){
                    JOptionPane.showMessageDialog(this, "Login Gagal");
                    tfUsername.setText("");
                    pfPassword.setText("");
                }
                rs.close();
                ps.close();
                

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terdapat Masalah Ke Database"+ex.toString());
            }
      
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
        pfPassword.requestFocus();
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
        bLogin.requestFocus();        
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
        // TODO add your handling code here:
        new Admin(user);
        new KedaiHp(user);
    }//GEN-LAST:event_bLoginMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
